GrupparbeteMVC/Models/Product.cs
using Azure;

namespace GrupparbeteMVC.Models
{
    public class Product
    {
        public int Id { get; set; }

        public string? Name { get; set; }

        public string? Description { get; set; }

        public decimal? SEKPrice { get; set; }

        public decimal? DollarPrice { get; set; }

        public List<Category>? Categories { get; set; }

        public List<Tag>? Tags { get; set; }

        public List<Order>? Orders { get; set; }
    }
}

GrupparbeteMVC/Controllers/CartsController.cs
using GrupparbeteMVC.Models;
using GrupparbeteMVC;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using GrupparbeteMVC.Models.ViewModels;

namespace Grupparbete.Controllers
{
    public class CartsController : Controller
    {
        public readonly ApplicationContext Context;
        public CartsController(ApplicationContext context)
        {
            Context = context;
        }

        public IActionResult AddToCart(int id)
        {
            Product CurrentProduct = Context.Products.FirstOrDefault(x => x.Id == id);
            CartItem ExistingCartItem = Context.CartItems.FirstOrDefault(x => x.CartId == 1 && x.ProductId == CurrentProduct.Id);
            if (ExistingCartItem != null)
            {
                ExistingCartItem.Quantity = ExistingCartItem.Quantity + 1;
                ExistingCartItem.CartItemTotal = ExistingCartItem.CartItemTotal + CurrentProduct.SEKPrice;
                Context.CartItems.Update(ExistingCartItem);

                Cart Cart = Context.Carts.FirstOrDefault(x => x.Id == 1);
                Cart.CartTotal = Cart.CartTotal + CurrentProduct.SEKPrice;
                Context.SaveChanges();
            }
            else
            {
                CartItem CartItem = new CartItem();
                CartItem.ProductId = CurrentProduct.Id;
                CartItem.Quantity = 1;
                CartItem.CartItemTotal = CurrentProduct.SEKPrice;
                Cart Cart = Context.Carts.FirstOrDefault(x => x.Id == 1);
                //  Cart.Date = DateTime.Now;
                Cart.CartTotal = Cart.CartTotal + CartItem.CartItemTotal;
                Cart.CartItems = new List<CartItem>();
                Cart.CartItems.Add(CartItem);
                Context.Carts.Add(Cart);
                Context.Carts.Update(Cart);
                Context.SaveChanges();
            }

            return RedirectToAction(nameof(Index));
        }
        public IActionResult Index()
        {
            Cart CurrentCart = Context.Carts.Include(cart => cart.CartItems).ThenInclude(cartItem => cartItem.Product).FirstOrDefault(cart => cart.Id == 1);
            return View(CurrentCart);
            /*
            Cart Cart = Context.Carts.Include(x => x.CartItems).FirstOrDefault(x => x.Id == 1);

            return View(Cart);
            */
        }

        public IActionResult Delete(int Id)
        {

            
          
            CartItem CartItem = Context.CartItems.FirstOrDefault(x => x.Id == Id);
            Product CurrentProduct = Context.Products.FirstOrDefault(x => x.Id == CartItem.ProductId);

            // Skapar en viewmodel för att kunna skriva ut namnet på produkten i View filen.
            var viewModel = new CartItemProduct();
            viewModel.cartItem = CartItem;
            viewModel.product = CurrentProduct;

      

            return View(viewModel);
         

        }
        public IActionResult DeleteConfirm(int Id)
        {
            CartItem CartItem = Context.CartItems.FirstOrDefault(x => x.Id == Id);
            Context.CartItems.Remove(CartItem);
            Context.SaveChanges();

            //Updaterar det totala priset i varukorgen
            Cart CurrentCart = Context.Carts.FirstOrDefault(x => x.Id == 1);
            CurrentCart.CartTotal = CurrentCart.CartTotal - CartItem.CartItemTotal;
            Context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult DeleteAll()
        {
            var cartItems = Context.CartItems.ToList();
            foreach (var cartItem in cartItems)
            {
                Context.CartItems.Remove(cartItem);
            }
            Cart CurrentCart = Context.Carts.FirstOrDefault(x => x.Id == 1);
            CurrentCart.CartTotal = 0;

            Context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult DeleteAllConfirm()
        {
            List<CartItem> MyItems = Context.CartItems.ToList();
            return View(MyItems);
        }

        public IActionResult AddOne(int Id)
        {
            CartItem CartItem = Context.CartItems.FirstOrDefault(x => x.Id == Id);
            Cart CurrentCart = Context.Carts.FirstOrDefault(x => x.Id == 1);
            Product CurrentProduct = Context.Products.FirstOrDefault(x => x.Id == CartItem.ProductId);

            //Uppdaterar kvantiteten för den enskillda varan 
            CartItem.Quantity = CartItem.Quantity + 1;
            //Updaterar det totala priset i varukorgen
            CurrentCart.CartTotal = CurrentCart.CartTotal + CurrentProduct.SEKPrice;
            //Uppdaterar priset för den enskillda varan
            CartItem.CartItemTotal = CartItem.CartItemTotal + CurrentProduct.SEKPrice;
            Context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult RemoveOne(int Id)
        {
            CartItem CartItem = Context.CartItems.FirstOrDefault(x => x.Id == Id);
            Cart CurrentCart = Context.Carts.FirstOrDefault(x => x.Id == 1);
            Product CurrentProduct = Context.Products.FirstOrDefault(x => x.Id == CartItem.ProductId);

            // Om det bara finns 1st en vara så tas den bort om användaren trycker på minustecknet
            if (CartItem.Quantity == 1)
            {
                Context.CartItems.Remove(CartItem);
                Context.SaveChanges();

                //Updaterar det totala priset i varukorgen
                CurrentCart.CartTotal = CurrentCart.CartTotal - CurrentProduct.SEKPrice;
                //Uppdaterar priset för den enskillda varan
                CartItem.CartItemTotal = CartItem.CartItemTotal - CurrentProduct.SEKPrice;
                Context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            else
            {
                CartItem.Quantity = CartItem.Quantity - 1;
                Context.SaveChanges();

                CurrentCart.CartTotal = CurrentCart.CartTotal - CurrentProduct.SEKPrice;
                CartItem.CartItemTotal = CartItem.CartItemTotal - CurrentProduct.SEKPrice;
                Context.SaveChanges();
                return RedirectToAction(nameof(Index));

            }

        }





    }
}

GrupparbeteMVC/Controllers/ProductsController.cs
using GrupparbeteMVC.Models;
using GrupparbeteMVC;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Grupparbete.Controllers
{
    public class ProductsController : Controller
    {
        private readonly ApplicationContext Context;

        public ProductsController(ApplicationContext _context)
        {
            Context = _context;
        }
        public IActionResult Index()
        {
            List<Product> MyProducts = Context.Products.ToList();
            return View(MyProducts);
        }

        public IActionResult Details(int Id)
        {
            Product CurrentProduct = Context.Products.Include(p => p.Categories).Include(p => p.Tags).Where(p => p.Id == Id).FirstOrDefault();
            return View(CurrentProduct);
        }

        public IActionResult IndexDollarPrice()
        {
            List<Product> MyProducts = Context.Products.ToList();
            return View(MyProducts);
        }

        public IActionResult DetailsDollarPrice(int Id)
        {
            Product CurrentProduct = Context.Products.Include(p => p.Categories).Include(p => p.Tags).Where(p => p.Id == Id).FirstOrDefault();
            return View(CurrentProduct);
        }

    }
}

GrupparbeteMVC/Views/Products/Details.cshtml
@model GrupparbeteMVC.Models.Product

<h1> Details </h1>
<a asp-action="DetailsDollarPrice" asp-route-id="@Model.Id">Change to Dollar price</a>


<br />
Name: 
@Html.DisplayFor(model => model.Name)<br />

Description: 
@Html.DisplayFor(model => model.Description)<br />

Price: 
@Html.DisplayFor(model => model.SEKPrice)Kr
<br />

Categories:
<ul>
    @foreach (var category in Model.Categories)
    {
        <li>@category.Name</li>
    }
</ul>

Tags:
<ul>
    @foreach (var tag in Model.Tags)
    {
            <li>@tag.Name</li>
    }
</ul>

<a href="">Share on Twitter</a>
<br />
<a href="">Share on Instagram</a>
<br />

<a asp-controller="Carts" asp-action="AddToCart" asp-route-id="@Model.Id">Add to cart</a>

GrupparbeteMVC/Views/Products/DetailsDollarPrice.cshtml
@model GrupparbeteMVC.Models.Product

<h1> Details </h1>
<a asp-action="Details" asp-route-id="@Model.Id">Change to SEK price</a>

<br />
Name:
@Html.DisplayFor(model => model.Name)
<br />

Description:
@Html.DisplayFor(model => model.Description)
<br />

Price:
@Html.DisplayFor(model => model.DollarPrice)$
<br />

Categories:
<ul>
    @foreach (var category in Model.Categories)
    {
        <li>@category.Name</li>
    }
</ul>

Tags:
<ul>
    @foreach (var tag in Model.Tags)
    {
        <li>@tag.Name</li>
    }
</ul>

<a href="">Share on Twitter</a>
<br />
<a href="">Share on Instagram</a>
<br />

<a asp-controller="Carts" asp-action="AddToCart" asp-route-id="@Model.Id">Add to cart</a>

GrupparbeteMVC/Views/Products/Index.cshtml
@model List<Product>

<a asp-action="IndexDollarPrice">Change to Dollar price</a>
<br />
<br />
@foreach (Product Item in Model)
{
    <br />
    @Html.DisplayFor(modelItem => Item.Name)
    <br />
    @Html.DisplayFor(modelItem => Item.SEKPrice)
    <span>Kr </span>
    <br />

    <a asp-controller="Carts" asp-action="AddToCart" asp-route-id="@Item.Id"> Add to cart</a>
    <br />
     <a asp-action="Details" asp-route-id="@Item.Id">View Details</a> 
     <br />
}

GrupparbeteMVC/Views/Products/IndexDollarPrice.cshtml
@model List<Product>


    <a id="change-price-link" asp-action="Index">Change to SEK price</a>
    <br />
    <br />

<div id="products-list">
@foreach (Product Item in Model)
{
    <div class="product">
        <div class="product-name">@Html.DisplayFor(modelItem => Item.Name)</div>
        <div class="product-price">@Html.DisplayFor(modelItem => Item.DollarPrice)<span>$</span></div>
        <div class="product-actions">
            <a class="add-to-cart" asp-controller="Carts" asp-action="AddToCart" asp-route-id="@Item.Id">Add to cart</a>
            <a class="view-details" asp-action="DetailsDollarPrice" asp-route-id="@Item.Id">View Details</a>
        </div>
    </div>
}
 </div>